#!/usr/bin/bash
#
#PBS -l walltime=10:00:00
#PBS -l nodes=1:ppn=28
#PBS -N trim_run8
#PBS -j oe
#PBS -A PAS0536
#PBS -m abe

cd $PBS_O_WORKDIR
module load java
module load trimmomatic

java -jar /usr/local/trimmomatic/Trimmomatic-0.36/trimmomatic-0.36.jar PE SRR8293759.1_1.fastq.gz SRR8293759.1_2.fastq.gz SRR8293759_paired1_t8 SRR8293759_unpaired1_t8 SRR8293759_paired2_t8 SRR8293759_unpaired2_t8 ILLUMINACLIP:adapters.fasta:2:30:10 MAXINFO:50:0.5 LEADING:3 TRAILING:3 SLIDINGWINDOW:10:15 MINLEN:36
java -jar /usr/local/trimmomatic/Trimmomatic-0.36/trimmomatic-0.36.jar PE SRR8451905.1_1.fastq.gz SRR8451905.1_2.fastq.gz SRR8451905_paired1_t8 SRR8451905_unpaired1_t8 SRR8451905_paired2_t8 SRR8451905_unpaired2_t8 ILLUMINACLIP:adapters.fasta:2:30:10 MAXINFO:50:0.5 LEADING:3 TRAILING:3 SLIDINGWINDOW:10:15 MINLEN:36
